### ISSUE TITLE
Add settings to adjust the minimum and maximum precipitation rates

### ISSUE THREAD

**Issue by oriolprogamer712** [TalonFloof/EnhancedWeather#10]
add that you can make the rainfall have a value and edit it to have a maximum rate and a minimum rate.

**Comment by Talon396** [comment]
Hi, @oriolprogamer712. Adding a setting for the minimum rainfall wouldn't make any sense, since it would allow rainfall to occur even when there is no rain cloud. However, I can add a setting for the maximum rate.
