### ISSUE TITLE
Black Clouds when vanilla fog is disabled

### ISSUE THREAD

**Issue by Omni-MC** [TalonFloof/EnhancedWeather#21]
**Describe the bug**
I suspect this to be an oversight, due to how this mod handles fog, more than a "bug"

**To Reproduce**
Install Distant Horizons and Enhanced Weather

**Expected behavior**
Distant clouds should be the same shade

**Screenshots**
[Clouds in the distance are black](https://media.essential.gg/c28e36c4-3a78-468e-a15e-329096d54f00)
[Distant Horizons fog settings](https://media.essential.gg/b73a2926-5717-4957-c682-71e8a5f61b00)

**System Information:**
- Minecraft Version: 1.19.4
- Fabric/Quilt Loader Version: 0.14.19
- Fabric API Version: 0.81.1+1.19.4
- EnhancedWeather Version: 1.0-Beta5.2
- Loaded mods: A lot, but I'm certain only these two are of concern.

**Additional context**
As stated above, I'm certain this is nothing more than an oversight. 
Sidenote: Cloud particles are ridiculously large and opaque and lots of clipping. The clipping is very likely only so noticeable because the particle textures are shaded. Sort of looks like a choppy fluid

**Comment by Omni-MC** [comment]
Absolutely uncertain what changed but when reloading resources it seems to have solved itself. However, I suspect the particle textures have pixels with very little opacity on the edges which makes the clipping worse, cutting holes in other particles.

**Comment by TalonFox** [comment]
Yeah, Minecraft renders the cloud particles in a very unusual way. I've known about rendering issues like this for a while now, but haven't been able to figure out the root cause of them. You may be on to something though.
