### ISSUE TITLE
Issues with Shader Compatibility

### ISSUE THREAD

**Issue by Birbman13** [TalonFloof/EnhancedWeather#22]
While using Sildur's Vibrant Shaders Lite, the clouds are flickering a lot.

Any clip I have tried to send has had too large of a file size, but I will describe the steps on how to recreate.

Have Iris installed on fabric
Use Sildur's Vibrant Lite
Wait for large cloud to form.

The edges are very flickery, and it doesn't do that without shaders on.

**Comment by TalonFox** [comment]
Yeah, this is another rendering issue that I've known about since I started working on the mod, at the moment I haven't figured out a way of fixing it due to the way particles work with shaders, but I'll still keep this issue open.
