### ISSUE TITLE
Feature: Cloud visibility improvement 

### ISSUE THREAD

**Issue by Landon-9999** [TalonFloof/EnhancedWeather#24]
**Is your feature request related to a problem? Please describe.**
The cloud system really needs to be replaced or changed drastically. Got several people on my server saying they can't see when in mountains. And they can't see the sun/moon at all hardly. And particles cull oddly sometimes causing minor flickering

**Describe the solution you'd like**
Change to some other method of display for location-based clouds or reduce transparency by default?

**Describe alternatives you've considered**
This mod below would look really good but I don't know how difficult it would be to integrate with.
https://modrinth.com/mod/better-clouds

**Additional context**
none

**Comment by TalonFox** [comment]
I'm actually in the progress of rewriting this mod so this shouldn't be a problem soon
