### ISSUE TITLE
Dimension Blacklist/Whitelist

### ISSUE THREAD

**Issue by PolyframeX** [TalonFloof/EnhancedWeather#33]
Is it possible to add a feature to disable the clouds entirely in a certain dimension? Clouds start to appear in certain dimensions that wouldn't make much sense such as moons.

It would be nice if a config for a whitelist/blacklist was added where you can list dimensions you want the clouds to load in, and dimensions for it to not load in.

Alternatively you can just have it only use the overworld, however it would be preferred to be a simple blacklist/whitelist

**Comment by TalonFloof** [comment]
This is definitely something I will add, thank you for opening this issue.

**Comment by TalonFloof** [comment]
Fixed in the latest version
