### ISSUE TITLE
Config file is empty.  enhancedweather.Json5  [1.1-Alpha1]

### ISSUE THREAD

**Issue by Redstonize** [TalonFloof/EnhancedWeather#35]
Tested with (any version of) clothconfig, fabric-api.
Tested with and without Mod-menu.
No other mods.

The config file for the mod is not written to / does not contain information, thus won't save anything from ingame configuration (using Mod-menu.) This occurs at game launch.
![image](https://github.com/TalonFloof/EnhancedWeather/assets/5296592/2405150d-757b-4676-8cfe-19eb291cb052)
![image](https://github.com/TalonFloof/EnhancedWeather/assets/5296592/66529922-7f6d-421e-89b7-a6cdf792f2d2)

**Comment by TalonFloof** [comment]
Strange, I'll look into that

**Comment by TalonFloof** [comment]
Fixed in the latest version
