### ISSUE TITLE
clouds generating in dimensions they shouldn't

### ISSUE THREAD

**Issue by Pigfection** [TalonFloof/EnhancedWeather#39]
![2024-03-21_14 56 56](https://github.com/TalonFloof/EnhancedWeather/assets/80092243/d2eed594-40a0-4179-8654-8eb97560334c)

I've got Ad Astra installed and was wondering if its possible to add a dimensions blacklist/whitelist to prevent clouds spawning in dimensions we don't want them to exist in. Would be helpful thanks!

**Comment by TalonFloof** [comment]
Okay yea, that needs to be fixed

**Comment by TalonFloof** [comment]
Was fixed in the latest update

**Comment by Pigfection** [comment]
> Was fixed in the latest update

is there a possibility to get this in 1.20.1?

**Comment by TalonFloof** [comment]
I just backported it to 1.20.1 :3

**Comment by Pigfection** [comment]
thanks very much
